services:
#  keycloak:
#    image: bitnami/keycloak:21.1.2
#    container_name: keycloak
#    environment:
#      DB_VENDOR: POSTGRES
#      DB_ADDR: postgres
#      DB_DATABASE: keycloak_db
#      DB_USER: ${POSTGRES_USER:-postgres}
#      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin_password
#    ports:
#      - "8484:8080"
#    depends_on:
#      - user-db
#    links:
#      - "user-db:postgres"
#
#  user-db:
#    container_name: user-db
#    image: library/postgres
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER:-postgres}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
#      POSTGRES_DB: keycloak_db
#    ports:
#      - "5454:5432"
#    restart: unless-stopped

  task-db:
    image: postgres:16.1
    container_name: task-db
    ports:
      - "5453:5432"
    environment:
      - POSTGRES_DB=task
      - POSTGRES_USER=task
      - POSTGRES_PASSWORD=task
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  main-service:
    build: main-service
    container_name: main-service
    ports:
      - "8081:8080"
    depends_on:
      - task-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://task-db:5432/task
      - SPRING_DATASOURCE_USERNAME=task
      - SPRING_DATASOURCE_PASSWORD=task