create table tasks (
        id bigint generated by default as identity,
        owner_id bigint not null,
        executor_id bigint,
        name varchar(50) not null unique,
        commit varchar(255),
        description varchar(255),
        priority_task varchar(255) check (priority_task in ('HIGH','MEDIUM','LOW')),
        status_task varchar(255) check (status_task in ('PENDING','PROGRESS','COMPLETED')),
        primary key (id)
    );

create table roles (
        id bigint generated by default as identity,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

create table users (
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        password varchar(255) not null,
        primary key (id)
    );

create table users_roles (
    roles_id bigint not null,
    user_id bigint not null
);

alter table if exists users_roles
       add constraint FKa62j07k5mhgifpp955h37ponj
       foreign key (roles_id)
       references roles;

alter table if exists users_roles
       add constraint FK2o0jvgh89lemvvo17cbqvdxaa
       foreign key (user_id)
       references users
